PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT COUNT(DISTINCT(?person0)) AS ?personCount0 
WHERE 
{ 
	GRAPH ?Gperson0 
	{ 
		?person0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> . 
	} 
	
	GRAPH <http://app.magi/graphs> 
	{ 
		?Gperson0 <http://xmlns.com/foaf/0.1/primaryTopic> ?person0 . 
	} 
}